import { ElementRef, EventEmitter, NgZone, OnDestroy, OnInit, Renderer2 } from '@angular/core';
import { WarpViewComponent } from '../warp-view-component';
import { SizeService } from '../../services/resize.service';
import { DataModel } from '../../model/dataModel';
export declare class WarpViewEventDropComponent extends WarpViewComponent implements OnInit, OnDestroy {
    el: ElementRef;
    renderer: Renderer2;
    sizeService: SizeService;
    ngZone: NgZone;
    elemChart: ElementRef;
    set type(type: string);
    set hiddenData(hiddenData: number[]);
    pointHover: EventEmitter<any>;
    warpViewChartResize: EventEmitter<any>;
    chartDraw: EventEmitter<any>;
    boundsDidChange: EventEmitter<any>;
    private visibility;
    private maxTick;
    private minTick;
    private visibleGtsId;
    private _type;
    private eventConf;
    constructor(el: ElementRef, renderer: Renderer2, sizeService: SizeService, ngZone: NgZone);
    ngOnInit(): void;
    ngOnDestroy(): void;
    update(options: any, refresh: any): void;
    updateBounds(min: any, max: any): void;
    drawChart(): void;
    protected convert(data: DataModel): any[];
}
