/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  QuantumChart as QuantumChart
} from './components/quantum-chart/quantum-chart';

declare global {
  interface HTMLQuantumChartElement extends QuantumChart, HTMLStencilElement {
  }
  var HTMLQuantumChartElement: {
    prototype: HTMLQuantumChartElement;
    new (): HTMLQuantumChartElement;
  };
  interface HTMLElementTagNameMap {
    "quantum-chart": HTMLQuantumChartElement;
  }
  interface ElementTagNameMap {
    "quantum-chart": HTMLQuantumChartElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "quantum-chart": JSXElements.QuantumChartAttributes;
    }
  }
  namespace JSXElements {
    export interface QuantumChartAttributes extends HTMLAttributes {
      chartTitle?: string;
      data?: string;
      options?: object;
      responsive?: boolean;
      type?: string;
      unit?: string;
    }
  }
}


import {
  QuantumScatter as QuantumScatter
} from './components/quantum-scatter/quantum-scatter';

declare global {
  interface HTMLQuantumScatterElement extends QuantumScatter, HTMLStencilElement {
  }
  var HTMLQuantumScatterElement: {
    prototype: HTMLQuantumScatterElement;
    new (): HTMLQuantumScatterElement;
  };
  interface HTMLElementTagNameMap {
    "quantum-scatter": HTMLQuantumScatterElement;
  }
  interface ElementTagNameMap {
    "quantum-scatter": HTMLQuantumScatterElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "quantum-scatter": JSXElements.QuantumScatterAttributes;
    }
  }
  namespace JSXElements {
    export interface QuantumScatterAttributes extends HTMLAttributes {
      chartTitle?: string;
      data?: string;
      options?: object;
      responsive?: boolean;
      type?: string;
      unit?: string;
    }
  }
}


import {
  QuantumTile as QuantumTile
} from './components/quantum-tile/quantum-tile';

declare global {
  interface HTMLQuantumTileElement extends QuantumTile, HTMLStencilElement {
  }
  var HTMLQuantumTileElement: {
    prototype: HTMLQuantumTileElement;
    new (): HTMLQuantumTileElement;
  };
  interface HTMLElementTagNameMap {
    "quantum-tile": HTMLQuantumTileElement;
  }
  interface ElementTagNameMap {
    "quantum-tile": HTMLQuantumTileElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "quantum-tile": JSXElements.QuantumTileAttributes;
    }
  }
  namespace JSXElements {
    export interface QuantumTileAttributes extends HTMLAttributes {
      type?: string;
      url?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
